app/app.tsx
app/i18n/en.ts
app/navigators/AppNavigator.tsx
app/screens/DashboardHomeScreen.tsx
app/screens/NotificationsScreen.tsx
app/theme/styles.ts

Added the bare skeleton for the notifications page with filler icons for now
https://github.com/user-attachments/assets/351c82a0-dae4-4818-b213-da3665bc3e4f
Unfortunately for the `Stack.Screen` parameter there isn't a `slide_from_top` for the `animation` prop so it's currently a fade which deviates slightly from the Figma. 
`presentation: "fullScreenModal"` is added as it makes the modal transition (and hence the fade) faster.
Hardcoded absolute values for `top` and `right` are added as placeholders for now, they are likely to change since they're probably going to sit in another `header` component for our dashboard home screen.

WR-87 feat(notifications): add notifications skeleton page

---

app/tamagui.config.ts

Ticket: https://comp30022weroster2025s2.atlassian.net/browse/WR-85
Added token definitions for our defined colour themes; so now colours are standardised and can be used like this:
YIPPEEE

WR-85 feat: :wrench: define colour tokens

---

app/screens/DashboardHomeScreen.tsx

Fix this error which appears on both ios and android build:
---
</details>

NO-000 fix(general): fix string in text component bug

---

.github/workflows/ping-discord.yml

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-110)_
Fulfilled required functionality:
(1) If you request someone for a PR it should ping them 
(2) If someone leaves a review it should ping the PR owner
(3) In the discord ping there should be a link to the PR
---
</details>

WR-110 feat(general): add discord pings for pr activity

---

app/components/Lozenge.tsx
app/screens/DashboardHomeScreen.tsx

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-109)_
- Created a `Lozenge` component that takes in the props: `type`, `active` and `onPress`
- `active` and `onPress` are optional to distinguish between the status lozenges and the filter lozenges.
iOS: 
Android:
Demo:
https://github.com/user-attachments/assets/f5a6aa87-fb7d-467c-987a-0c50a97eeec4
Demo code:
Follow-up ticket to update typographies: https://comp30022weroster2025s2.atlassian.net/browse/WR-113
---
</details>

WR-109 feat(general): ✨ Create status lozenge component

---

.github/workflows/ping-discord.yml

TO QA:
- Cycle through the different review statuses to check that those pings still work (comment, request changes, approve)
- Ill comment on my own PR in reply to one of your comments and there shouldn't be another ping sent
---
</details>

NO-00 fix(general): fix discord ping to not include self review comments

---

.github/workflows/enforce-rebase.yml
.github/workflows/trigger-rebase-check

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-111)_
CI check to ensure that a branch is directly on top of main (rebased) before allowing merges.
The first commit adds a CI check which runs each time you push to a PR, ensuring that a PR has been rebased on the latest version of main
When CI is run at a certain point in time and all is green, if someone pushes to main, updating it, the CI check remains green. This creates an inconsistency between the (outdated) check saying that a PR has been rebased onto the latest version of main when it really hasn't been. To fix this:
The second commit adds another workflow which runs each time someone pushes to main. This re-triggers the rebase check on open PRs, marking them as stale (no longer on the latest version of main). …

WR-111 ci(general): enforce rebasing prior to merging into main

---

app/components/TeamRosterShiftTabBar.tsx

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-105)_
Added team roster shift tab component for filtering the dates
Parent component will need a useState that holds the "AM" "PM" "AH" state, like the following
Note that the `sections` const is defined inside the component in order to access `useTheme()` hook, otherwise it wouldve been nice to have it outside the component as a constant map
```javascript
const [timeSection, setTimeSection] = useState<"AM" | "PM" | "AH">("AM")
<TeamRosterShiftTabBar timeSection={timeSection} setTimeSection={setTimeSection} />
```
https://github.com/user-attachments/assets/ebec66e7-cf77-4399-89f9-c851d161c05d
---
</details>

WR-105 feat(team-roster): :sparkles: create team roster shift tab component

---

.github/workflows/trigger-rebase-check

Unfortunately you'll see that the "trigger-rebase-check" workflow isn't being triggered on main, reason being that it's my PAT token so when other people merge they don't have perms to use my token to re-trigger workflows... I couldn't have foreseen this when making it though because I test it as the same user and pushing to main would require me to assume the identity of another user (cloning the repo under a different git account) which is not worth it imo
Let's just change the token and see if it works, with CI QA'ing is a "merge and find out" situation D:
---
</details>

NO-00 fix(general): change trigger rebase workflow token

---

app/components/Lozenge.tsx
app/components/Tests/Lozenge.test.tsx

CURRENTLY ALL TESTS ARE PASSING
had to also add testID and accessibility states into the component so that I could test it (doesn't affect function), can comment out if not testing
---
</details>

WR-131 test(general): :white_check_mark: add tests for the lozenge component

---

.husky/pre-commit

Deleting tests from precommits cause they're too slow. I'll update the connie DX docs to be consistent after merge
---
</details>

NO-00 perf(general): remove tests from precommit hooks

---

app/app.tsx
app/services/hooks/useDashboardPreferences.ts
app/services/hooks/useProfile.ts
package-lock.json
package.json

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-146)_
Old hook data has now been cached! It loads in once on initial fetch and that's it (you can check the console logs for each time the endpoint is called if you want to confirm).
[Made a decision doc](https://comp30022weroster2025s2.atlassian.net/wiki/spaces/CWR2/pages/72056835/W9+Data+Fetching+Methodology+Tanstack+Query) on why this change is so so so much better than what we were doing before. This PR just handles existing GETs but `useMutation` is going to make making POSTs that much easier too.
1. Set up tanstack query: install and create query client for app entry
2. Replace my old manually created hooks (`useProfile` and when merged and `useDashboardPreferences`) with tanstack query
**NOTES:**
We might want …

WR-146 feat(api): set up tanstack query

---

app/screens/RosterScreen/MyRosterScreen.tsx
app/services/api/eventApi.ts
app/services/hooks/useMyShifts.ts
backend/src/routes/event.routes.ts
backend/src/services/event.service.ts
backend/src/types/event.types.ts

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-121)_
now that tanstack query is merged in, updated to use tanstack AND
- added extra field numUsers for FE to leverage
- extended EventData type and used that for this hook instead --> justification is not every fetch of the EventData will need Event Assignment, and modifying the original type itself is not truthful to the DB, so extending it feels the most correct for an extension of the original datatype
note the "with 3 users" etc.
now that WR-128 is merged, updated FE services to be in designated eventsApi.ts
- fetching user id + first name + last name
- note that I did not fetch the entire user model, I think that if they click into something and segue into a new page, there should be a refetch given the selected …

WR-121 feat(api): build fetch api for my shifts

---

backend/src/middleware/auth.middleware.ts
backend/src/services/auth.service.ts

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-123)_
Separate PR to address accessing the user's hospital ID through API requests, as needed here: https://github.com/rcchao/weroster-team41/pull/81/files#r2400779059
Auth context and MMKV storage is exclusively for the frontend auth context, not for the backend. In order to have the backend gain access to the user's hospital ID as a global context the same way we do for the user IDs, I've added that field in to what we need for JWT token signing and decoding
Note that in order for you to make use of the user's hospital ID and see the results in e.g. postman, you'll need to regenerate the bearer token (as it is now signed differently!) and use that for your requests. I've added in a console.log to make this …

WR-123 feat(auth): expose user hospital id in requests

---

app/components/RosterCalendar.tsx
app/screens/RosterScreen/MyRosterScreen.tsx
package-lock.json
package.json

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-145)_
- Implemented the base `react-native-calendar` calendar and passed in event data using the `useEvents()` hook.
- Note that the calendar must sit in the screen on its own, as the `CalendarProvider` component provides its own scrolling (wrapping it in `Screen` or `View` messed with it). 
iOS:
https://github.com/user-attachments/assets/b0c39b2e-0183-41e4-a0f0-d2857f9a9d97
Android:
https://github.com/user-attachments/assets/3b518b29-51c3-444a-ba8b-65ce2164cef8
---
</details>

WR-145 feat(my-roster): Create base calendar component with event data

---

app/screens/RosterScreen/OpenShiftsScreen.tsx
app/services/api/eventApi.ts
app/services/hooks/useOpenShifts.ts
backend/src/routes/event.routes.ts
backend/src/services/event.service.ts

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-125)_
need to clarify with client, but for our purposes right, I am treating an open shift as a **shift with 0 users assigned to it**
obv some real world flaws with this assumption but we can roll with this for now considering this is a FE refresh
Response shapes are identical to MyRoster (myShifts api + hook), just with an additional where clause of no users (plus same hospital ID) -> this is so that the FE components that handle shifts can expect the same type!!
API Response:
```
{
"success": true,
"data": [
{
"id": 18,
"start_time": "2025-01-29T08:00:00.000Z",
"end_time": "2025-01-29T14:00:00.000Z",
"on_call": true,
"activity": {
"id": 2,
"name": "Cardiac Surgery",
"group_id": 1,
"location_id": 2
},
"location": { …
```

WR-125 feat(open-shifts): build fetch api for open shifts

---

app/components/Lozenge.tsx
app/components/RequestCard.tsx
app/components/RequestTypeIcon.tsx

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-167)_
Commits:
1. Components need to have matching params with what is provided by the backend. E.g LEAVE is provided by the backend but the component accepts Leave 
2. Allows request cards to support multiple days and passed in leave types as an optional parameter so that it can be rendered.
Before:
After:
What the cards look like on ios and android:
Note:  I've updated the changelogs for all components touched on confluence
---
</details>

WR-167 refactor(general): make related components match requirements for requests page

---

app/components/TeamMemberCard.tsx

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-169)_
Updated connie docs
Commit 1:
- Added `startDate`, `endDate`, `role` and `location` as props for the card to be displayed
- Added date styling where the date is included for shifts and overnight shifts include both the start and end date for clarity
Commit 2:
Made the spacing and margins of the user card more similar to the figma
Before commit 2:
After commit 2:
Figma:
iOS and android:
---
</details>

WR-169 feat(team-roster): alter team member card

---

app/components/ShiftDetailsSubheader.tsx

- Created a `ShiftDetailsSubheader` component that takes in `start`, `end` and `session`. 
- Note that the `backgroundColor` on the duration will default to "$white100" when there is no `EventSession` on the `Event` object (may need to consider backfilling).
iOS:
Android:
---
</details>

WR-142 feat(my-roster): Create ShiftDetailsSubheader component

---

app/components/ShiftDetailCard.tsx

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-156)_
When clicking on a specific shift, this should segue to a shift details page which will hold this
To QA (dont QA):
`const { myShifts } = useMyShifts()`
`{myShifts && <ShiftDetailCard shift={myShifts[0]} />}`
My Shift:
Open Shift:
---
</details>

WR-156 feat(my-roster): create shift details component

---

app/screens/RosterScreen/TeamRosterScreen.tsx
app/services/api/eventApi.ts
app/services/hooks/useTeamShifts.ts
backend/src/routes/event.routes.ts
backend/src/services/event.service.ts
backend/src/types/event.types.ts

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-126)_
API for roster view -> team-roster
I'm undecided whether to keep or omit the current user's shifts here -> for now I have included them since I think it makes sense that you want to see your schedule w.r.t. everyone elses instead of flipping back and forth between MyRoster and TeamRoster
I tried to make the fields as minimal as possible to make this easy to work with
TO QA:
in postman: `http://localhost:3000/api/events/team-shifts?day=20&month=0&year=2025&Session=AM`
INTERSTINGLY WITH DATE FNS, MONTH IS ZERO-INDEXED!!!!!
so this is indexing for 2025 JANUARY 20th
Should see this event:
with 3 users:
API endpoint return shape
```
{
"success": true,
"data": [
{
"id": 1,
"name": "Main Campus",
"locations": [
{
"id": …
```

WR-126 feat(team-roster): build out team-roster api

---

app/components/RosterCalendar.tsx
app/screens/RosterScreen/MyRosterScreen.tsx

_[JIRA Ticket](https://comp30022weroster2025s2.atlassian.net/browse/WR-176)_
- Replace the`renderItem` JSX with the ShiftCard component in `RosterCalendar`
- Added styling to the section headers.
Adjusted:
iOS:
Android:
---
</details>

WR-176 feat(my-roster): Replace calendar items with customer component

---

app/components/DashboardTeamMemberCard.tsx

- Create a DashboardTeamMemberCard component.
- Decided to abbreviate name because truncating looked weird.
Adjusted:
iOS:
Android:
---
</details>

WR-187 feat(dashboard): Create DashboardTeamMemberCard component

---

.github/workflows/ci.yml
backend/jest.config.js
backend/package-lock.json
backend/package.json
backend/src/tests/teamMemberData.test.ts
package.json

Commit 1: Set up jest tests in backend -> `cd backend && npm run test` runs backend jest tests
Commit 2: Make test for team member data api
Each event assignment is the most upcoming assignment of the user
- We have 2 users, user 2 has events on Mon, Weds and Thurs and user 3 has events on Mon and Fri. The current day is Tues so we expect the most upcoming event assignment for user 2 to be Weds while for user 3, it should be Friday.
Commit 3: Configure api unit tests to run in CI. Separate frontend jest tests and backend jest tests (they have different dependencies so they can't all be run from the root directory with `npm jest`)
Without a test database we can't test the actual API so this was a good exercise in futility.. If we're emulating the sql queries in our test logic instead of …

WR-165 test(api): test team member data api
